apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiendatienda
spec:
  selector:
    matchLabels:
      name: tiendatienda
  template:
    metadata:
      labels:
        name: tiendatienda
    spec:
      containers:
        - image: oth4r/tiendatienda:master
          name: tiendatienda
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP