apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tiendatienda
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "*"
  #  nginx.ingress.kubernetes.io/rewrite-target: /
  # cambiar 20.72.99.142 por el IP de tu Ingress 
spec:
  ingressClassName: nginx
  rules:
  - host: tiendatienda.20.121.76.163.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: tiendatienda
            port:
              number: 80